-- 006_remote_schema_sync.sql
--
-- AUTO-GENERATED by `supabase db pull` on 2026-07-07, reconciling this repo's
-- migration files (001-005) against the actual live "argus" Supabase project.
-- This is what `db pull` found live that no local migration file accounted for:
--
-- 1. rls_auto_enable() + event trigger `ensure_rls` — a live safeguard that
--    force-enables Row Level Security on any new table created in `public`,
--    automatically. This exists on the live project only; no migration file
--    ever created it (someone added it by hand in the SQL editor).
-- 2. security_events.user_id is NOT NULL live; 004's ALTER didn't set that.
-- 3. document_chunks.trust_level has a CHECK constraint live restricting it to
--    ('user_query','retrieved','web_scraped','agent_gen'); 004 didn't add one.
-- 4. Live has ONE combined RLS policy "own security events" (all commands via
--    USING), not the two separate insert/select policies 004 defines. This
--    means the live policy differs in shape from what 004 says should exist —
--    reconcile by hand if you ever re-run 004 against a fresh database.
--
-- Everything else here (pg_net extension, default sequence privileges) is
-- Supabase platform noise, not app-relevant.
SET check_function_bodies = false;
DROP EXTENSION pg_net;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM service_role;
CREATE OR REPLACE FUNCTION public.match_document_chunks(query_embedding public.vector, match_collection_id uuid, match_count integer DEFAULT 5)
 RETURNS TABLE(id uuid, document_id uuid, content text, chunk_index integer, trust_level text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    document_chunks.id,
    document_chunks.document_id,
    document_chunks.content,
    document_chunks.chunk_index,
    document_chunks.trust_level,
    1 - (document_chunks.embedding <=> query_embedding) as similarity
  from document_chunks
  join documents on documents.id = document_chunks.document_id
  where documents.collection_id = match_collection_id
    and document_chunks.user_id = auth.uid()
  order by document_chunks.embedding <=> query_embedding
  limit match_count;
$function$;
CREATE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;
ALTER TABLE public.security_events ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE public.document_chunks ADD CONSTRAINT document_chunks_trust_level_check CHECK (trust_level = ANY (ARRAY['user_query'::text, 'retrieved'::text, 'web_scraped'::text, 'agent_gen'::text]));
CREATE POLICY "own security events" ON public.security_events USING ((user_id = auth.uid()));
CREATE EVENT TRIGGER ensure_rls ON ddl_command_end WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') EXECUTE FUNCTION public.rls_auto_enable();
